name: Meadow 💮 Bug Report
description: Create a bug report for Meadow Design System 💮.
labels: ['status: waiting for maintainer']
body:
  - type: markdown
    attributes:
      value: Thank you for creating an issue. Please include a concise, descriptive summary of the problem in the title above.
  - type: input
    attributes:
      label: Search terms
      description: |
        Your issue may already exist. First, check the [existing issues](https://github.com/Tractor-Supply-Ecommerce/tsc-storybook-design-system/issues?q=is%3Aopen+is%3Aclosed) for duplicates. If none match, please include the search terms you used so future users can find this issue more easily.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Latest version
      description: We incorporate bug fixes, performance enhancements, and other improvements into each new release.
      options:
        - label: I have confirmed that this issue exists in the latest version of Meadow 💮.
          required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        **⚠️ Issues that we are unable to reproduce cannot be resolved.**

        Please include a link to a live example and clear, step-by-step instructions for reproducing this bug.
      value: |
        Steps:
        1. Open this link to production example: (required)
        2.
        3.
  - type: textarea
    attributes:
      label: Current behavior
      description: Describe what happens instead of the expected behavior.
  - type: textarea
    attributes:
      label: Expected behavior
      description: Describe what should happen.
  - type: textarea
    attributes:
      label: Context
      description: What are you trying to accomplish? Providing context helps us come up with a solution that is more useful in the real world.
  - type: markdown
    attributes:
      value: |
        ## :heart: Love Material UI?

        Consider donating $10 to sustain our open-source work: [https://opencollective.com/mui-org](https://opencollective.com/mui-org).
