name: Documentation feedback
description: Improve documentation about Meadow Design System.
labels: ['status: waiting for Meadow Team', 'support: docs-feedback']
title: '[docs] '
body:
  - type: markdown
    attributes:
      value: Thank you for creating an feature request. Please include a concise, descriptive summary of the feature in the title above.
  - type: input
    attributes:
      label: Search terms
      description: |
        Your feature may already exist. First, check the [existing issues](https://github.com/Tractor-Supply-Ecommerce/tsc-storybook-design-system/issues?q=is%3Aopen+is%3Aclosed) for duplicates. If none match, please include the search terms you used so future users can find this issue more easily.
    validations:
      required: true
  - type: input
    id: page-url
    attributes:
      label: Related page
      description: Which page of the documentation ?
      placeholder: https://mui.com/material-ui/
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Kind of issue
      description: What kind of problem are you facing?
      options:
        - Unclear explanations
        - Missing information
        - Broken demo
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Issue description
      description: |
        Let us know what went wrong when you were using this documentation and what we could do to improve it.
  - type: textarea
    attributes:
      label: Context
      description: What are you trying to accomplish? Providing context helps us come up with a solution that is more useful in the real world.
