name: Feature request
description: Suggest a new idea for Meadow Design System.
labels: ['status: waiting for Meadow Team']
body:
  - type: markdown
    attributes:
      value: Thank you for creating an feature request. Please include a concise, descriptive summary of the feature in the title above.
  - type: input
    attributes:
      label: Search terms
      description: |
         Your feature may already exist. First, check the [existing issues](https://github.com/Tractor-Supply-Ecommerce/tsc-storybook-design-system/issues?q=is%3Aopen+is%3Aclosed) for duplicates. If none match, please include the search terms you used so future users can find this issue more easily.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Latest version
      description: We incorporate bug fixes, performance enhancements, and other improvements into each new release.
      options:
        - label: I have tested the latest version
          required: true
  - type: textarea
    attributes:
      label: Summary
      description: Describe how it should work.
  - type: textarea
    attributes:
      label: Examples
      description: Please include references to the relevant Meadow Design specification, other existing implementations, or screenshots demonstrating the expected behavior.
  - type: textarea
    attributes:
      label: Motivation
      description: What is your overarching goal? Adding detailed context helps us devise a more useful, real-world solution.
